version: '3.8'
services:
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - 8000:8000
    depends_on:
      - mongo
  
  message_service:
    build:
      context: ./message_service
      dockerfile: Dockerfile
    container_name: message_service
    ports:
      - 5000:5000
    depends_on:
      - mongo
  
  notification_service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    container_name: notification_service
    ports:
      - 5001:5001
    depends_on:
      - mongo

  
  tweet_service:
    build:
      context: ./tweet_service
      dockerfile: Dockerfile
    container_name: tweet_service
    ports:
      - 5002:5002
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_blog
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    ports:
      - '27017:27017'

  nginx:
    image: nginx
    container_name: nginx_blog
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - blog_service

volumes:
  mongo_data:
    external: true